swagger: "2.0"
info:
  title: echo server
  version: 0.0.1
paths:
  /hello:
    get:
      summary: returning hello world.
      description: returning hello world for test.
      responses:
        "200":
          description: return hellow world.
          schema:
            type: string
  /echo:
    post:
      summary: echo.
      description: echo.
      parameters:
        - name: message
          in: body
          required: true
          schema:
            type: string
      responses:
        "200":
          description: return the message.
          schema:
            type: string
  /board:
    post:
      summary: post a message to a board.
      description: post a message to a board.
      tags:
      - board
      operationId: PostMessage
      parameters:
        - name: massage
          in: body
          required: true
          schema:
            type: object
            properties:
              message:
                type: string
            required:
              - message
      responses:
        "200":
          description: message is successfully stored.

