// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostEchoOKCode is the HTTP code returned for type PostEchoOK
const PostEchoOKCode int = 200

/*PostEchoOK return the message.

swagger:response postEchoOK
*/
type PostEchoOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPostEchoOK creates PostEchoOK with default headers values
func NewPostEchoOK() *PostEchoOK {

	return &PostEchoOK{}
}

// WithPayload adds the payload to the post echo o k response
func (o *PostEchoOK) WithPayload(payload string) *PostEchoOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post echo o k response
func (o *PostEchoOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostEchoOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
