// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "title": "echo server",
    "version": "0.0.1"
  },
  "paths": {
    "/hello": {
      "get": {
        "description": "returning hello world for test.",
        "summary": "returning hello world.",
        "responses": {
          "200": {
            "description": "return hellow world.",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "title": "echo server",
    "version": "0.0.1"
  },
  "paths": {
    "/hello": {
      "get": {
        "description": "returning hello world for test.",
        "summary": "returning hello world.",
        "responses": {
          "200": {
            "description": "return hellow world.",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}`))
}
