// Code generated by go-swagger; DO NOT EDIT.

package board

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostMessageHandlerFunc turns a function with the right signature into a post message handler
type PostMessageHandlerFunc func(PostMessageParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostMessageHandlerFunc) Handle(params PostMessageParams) middleware.Responder {
	return fn(params)
}

// PostMessageHandler interface for that can handle valid post message params
type PostMessageHandler interface {
	Handle(PostMessageParams) middleware.Responder
}

// NewPostMessage creates a new http.Handler for the post message operation
func NewPostMessage(ctx *middleware.Context, handler PostMessageHandler) *PostMessage {
	return &PostMessage{Context: ctx, Handler: handler}
}

/* PostMessage swagger:route POST /board board postMessage

post a message to a board.

post a message to a board.

*/
type PostMessage struct {
	Context *middleware.Context
	Handler PostMessageHandler
}

func (o *PostMessage) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostMessageParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostMessageBody post message body
//
// swagger:model PostMessageBody
type PostMessageBody struct {

	// message
	// Required: true
	Message *string `json:"message"`
}

// Validate validates this post message body
func (o *PostMessageBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostMessageBody) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("massage"+"."+"message", "body", o.Message); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post message body based on context it is used
func (o *PostMessageBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostMessageBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostMessageBody) UnmarshalBinary(b []byte) error {
	var res PostMessageBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
