// Code generated by go-swagger; DO NOT EDIT.

package board

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostMessageOKCode is the HTTP code returned for type PostMessageOK
const PostMessageOKCode int = 200

/*PostMessageOK message is successfully stored.

swagger:response postMessageOK
*/
type PostMessageOK struct {
}

// NewPostMessageOK creates PostMessageOK with default headers values
func NewPostMessageOK() *PostMessageOK {

	return &PostMessageOK{}
}

// WriteResponse to the client
func (o *PostMessageOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
